config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources "contacts", only: [:new, :create]

  match '/home',    to: 'welcome#index',    via: 'get'
  match '/about',   to: 'welcome#about',    via: 'get'
  match '/news', 	to: 'welcome#news', 	via: 'get'
  match '/contact', to: 'contact#new',  	via: 'get'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Re: DJ-Kamikaze.com Message!",
      :to => "smpq103@yahoo.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def contact
	end

	def about
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "DJ Kamikaze"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.haml
%div
  - flash.each do |key, value|
    %div
      %a{"data-dismiss" => "alert", :href => "#"} ×
      = value

app/views/contacts/new.html.haml
.container
  .col-md-4.col-md-offset-4
    %div{:align => "center"}
      %h3{style: "margin-bottom:30px;"} Shoot me an email
      = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
        = f.input :name, :required => true
        = f.input :email, :required => true
        = f.input :message, :as => :text, :required => true
        .hidden
          = f.input :nickname, :hint => 'Leave this field blank!'
        %div
          = f.button :submit, 'submit', :class=> "btn btn-primary"

app/views/layouts/_footer.html.haml
%footer.footer.navbar-fixed-bottom
  %nav
    %ul
      %li
        %a{:href => "https://www.faebook.com/pages/DJ-Kamikaze/230957930288365", :target => "blank"}= image_tag "Facebook.png"
      %li
        %a{:href => "http://www.youtube.com/user/djmckamikazeshaun", :target => "blank"}= image_tag "Youtube.png"
      %li
        %a{:href => "https://twitter.com/DJKamikaze_", :target => "blank"}= image_tag "Twitter.png"
      %li
        %a{:href => "https://soundcloud.com/dj-kamikaze-1", :target => "blank"}= image_tag "Soundcloud.png"
      %li
        %a{:href => "http://www.mixcrate.com/djmckamikaze/dj_mixes", :target => "blank"}= image_tag "Mixcrate.png"

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .navbar-inner
      .container
        /
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar icon-ex"></span>
          <span class="icon-bar icon-ex"></span>
          <span class="icon-bar icon-ex"></span>
          </button>
        = link_to "welcome/index", '#', id: "logo"
        %nav
          %ul.nav.pull-right
            %li= link_to "Home",    '#'
            %li= link_to "Help",    '#'
            %li= link_to "Sign in", '#'

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#collapse-like-crazy", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        DJ Kamikaze

    .collapse.navbar-collapse#collapse-like-crazy
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "About", about_path
        %li
          = link_to "News", news_path
        %li
          = link_to "Contact", new_contact_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %title= full_title(yield(:title))
    = favicon_link_tag 'KamikazeFavicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    = render 'layouts/nav'

    = yield

    = render 'layouts/footer'

:javascript
  new WOW().init();
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52572778-1', 'auto');
  ga('send', 'pageview');

  (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));

app/views/welcome/about.html.haml
- provide(:title, 'About')
%h1 Biography
.well.about{style: "border: 1px solid #AFAFAF;"}
  %p
    %img.img-rounded{:align => "left", :src => "/assets/aboutMe.jpg", style: "margin: 8px 15px 0 -2px;"}
    It all started on Kaua'i after two years of Bible College: I
    wanted to become a DJ. I was 23 and had just gotten back
    home and had nothing going for me. I stumbled upon an ad on Craigslist
    from a radio station declaring they were looking for interns! The way I saw
    it was (1): I knew I was going to work for free at some point, (2): it was
    like free college, and (3): it'd be a fun job.
    %br
    %br
    I became the first paid intern out of the pool at that time and was responsible for
    an on-air shift for a hip hop, r&b, and dance hits station. I progressed toward
    being on two additional radio stations. This initial opportunity handed me a shot at becoming a party dj.
    It's an awesome feeling to mix beats in front of a crowd, and
    my mentors at the time constantly provided positive feedback. I eventually let the
    party life get the best of me and lost my job as both a radio and club dj.
    So I moved to Maui.
    %br
    %br
    With not much, I initially did a work trade for free rent deal. I felt trapped and fortunately moved on to another
    radio station company.
    I've met all kinds of characters throughout my career. A couple of people stood out:
    the money makers, the superstars, and the vultures. The
    money maker helped me kick my career off in the club; he's a great
    friend still to this day. The superstars were kind as well.
    It was the vulture who lost my trust.
    %br
    %br
    To bring us back into the present time; I'm now partnered with
    DJ Big Mike and All Access Entertainment. This has been the
    best part of my career as a DJ, a promoter, and an events coordinator.
    As a DJ I create mashups, remixes, and mixes for the people
    and those I DJ for in clubs or parties. I have worked with
    many big names but I am not much of a name dropper. If you
    need to know who, email me and we'll talk more. I am hoping still
    to put together more original music with various producers.
    %br
    %br
    I dream to dj on a global level for everyone one show at a time.
    I look forward to seeing you all one day. :)
    %br
    %br
    If you want to see what it is like for a dj coming up in this
    world, stay connected here.

app/views/welcome/index.html.haml
.container
  .center.hero-unit
    .wow.bounceInDown
      %center
        %img.img-responsive{:src => "assets/kamikaze-2.png"}

app/views/welcome/news.html.haml
- provide(:title, 'News')
%h1 News
#fb-root
.container
  .row
    .col-md-2
      %a.twitter-timeline{"data-widget-id" => "487004365853454336", :height => "400", :href => "https://twitter.com/DJKamikaze_", :width => "350"}
      :javascript
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      .fb-like-box{"data-colorscheme" => "light", "data-header" => "false", "data-height" => "350", "data-href" => "https://www.facebook.com/pages/DJ-Kamikaze/230957930288365", "data-show-border" => "true", "data-show-faces" => "true", "data-stream" => "false", "data-width" => "175"}
    .col-md-9.well
      %h3 Coming Soon...